"""initial_schema

Revision ID: e9380d077795
Revises: 
Create Date: 2026-05-23 22:25:38.791879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e9380d077795'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True, comment='用户名'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='操作动作'),
    sa.Column('resource_type', sa.String(length=50), nullable=True, comment='资源类型'),
    sa.Column('resource_id', sa.Integer(), nullable=True, comment='资源 ID'),
    sa.Column('resource_name', sa.String(length=200), nullable=True, comment='资源名称'),
    sa.Column('detail', sa.Text(), nullable=True, comment='操作详情 (JSON)'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='IP 地址'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='浏览器信息'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='操作状态'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False, comment='合同 ID'),
    sa.Column('contract_no', sa.String(length=50), nullable=False, comment='合同编号'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='合同名称'),
    sa.Column('contract_type', sa.String(length=50), nullable=True, comment='合同类型'),
    sa.Column('counterparty_name', sa.String(length=200), nullable=True, comment='相对方名称'),
    sa.Column('amount', sa.Float(), nullable=True, comment='合同金额'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='开始日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='结束日期'),
    sa.Column('approval_status', sa.String(length=20), nullable=True, comment='审批状态'),
    sa.Column('risk_level', sa.String(length=20), nullable=True, comment='风险等级'),
    sa.Column('creator_name', sa.String(length=50), nullable=True, comment='创建人姓名'),
    sa.Column('department_name', sa.String(length=100), nullable=True, comment='部门名称'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('signed_at', sa.DateTime(), nullable=True, comment='签署时间'),
    sa.Column('archived_at', sa.DateTime(), nullable=True, comment='归档时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ledger_contract', 'contract_ledger', ['contract_id'], unique=False)
    op.create_index('idx_ledger_counterparty', 'contract_ledger', ['counterparty_name'], unique=False)
    op.create_index('idx_ledger_no', 'contract_ledger', ['contract_no'], unique=False)
    op.create_index('idx_ledger_status', 'contract_ledger', ['status'], unique=False)
    op.create_index('idx_ledger_time', 'contract_ledger', ['created_at'], unique=False)
    op.create_index('idx_ledger_type', 'contract_ledger', ['contract_type'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_no', sa.String(length=50), nullable=False, comment='合同编号'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='合同名称'),
    sa.Column('contract_type', sa.String(length=50), nullable=False, comment='合同类型'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('counterparty_name', sa.String(length=200), nullable=False, comment='对方单位名称'),
    sa.Column('counterparty_type', sa.String(length=50), nullable=True, comment='对方类型'),
    sa.Column('counterparty_credit_code', sa.String(length=50), nullable=True, comment='统一社会信用代码'),
    sa.Column('amount', sa.Float(), nullable=True, comment='合同金额'),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True, comment='税率'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='开始日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='结束日期'),
    sa.Column('current_flow_id', sa.Integer(), nullable=True, comment='当前审批流程 ID'),
    sa.Column('approval_status', sa.String(length=20), nullable=True, comment='审批状态'),
    sa.Column('sign_date', sa.Date(), nullable=True, comment='签署日期'),
    sa.Column('sign_method', sa.String(length=20), nullable=True, comment='签署方式'),
    sa.Column('seal_record_id', sa.Integer(), nullable=True, comment='用印记录 ID'),
    sa.Column('archive_date', sa.Date(), nullable=True, comment='归档日期'),
    sa.Column('archive_location', sa.String(length=200), nullable=True, comment='归档位置'),
    sa.Column('creator_id', sa.Integer(), nullable=False, comment='创建人 ID'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='所属部门'),
    sa.Column('risk_level', sa.String(length=20), nullable=True, comment='风险等级'),
    sa.Column('content', sa.Text(), nullable=True, comment='合同内容'),
    sa.Column('current_version_id', sa.Integer(), nullable=True, comment='当前版本 ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_no')
    )
    op.create_index('idx_contract_no', 'contracts', ['contract_no'], unique=False)
    op.create_index('idx_counterparty', 'contracts', ['counterparty_name'], unique=False)
    op.create_index('idx_creator', 'contracts', ['creator_id'], unique=False)
    op.create_index('idx_department', 'contracts', ['department_id'], unique=False)
    op.create_index('idx_risk_level', 'contracts', ['risk_level'], unique=False)
    op.create_index('idx_status', 'contracts', ['status'], unique=False)
    op.create_index('idx_type', 'contracts', ['contract_type'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='部门名称'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父部门 ID'),
    sa.Column('level', sa.Integer(), nullable=True, comment='层级'),
    sa.Column('path', sa.String(length=500), nullable=True, comment='部门路径'),
    sa.Column('status', sa.Integer(), nullable=True, comment='1:启用 0:禁用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_department_parent', 'departments', ['parent_id'], unique=False)
    op.create_index('idx_department_path', 'departments', ['path'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='角色编码'),
    sa.Column('description', sa.Text(), nullable=True, comment='角色描述'),
    sa.Column('permissions', sa.Text(), nullable=True, comment='权限列表 (JSON)'),
    sa.Column('status', sa.Integer(), nullable=True, comment='1:启用 0:禁用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_role_code', 'roles', ['code'], unique=False)
    op.create_table('ai_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='合同版本 ID'),
    sa.Column('review_id', sa.String(length=50), nullable=False, comment='审查记录 ID'),
    sa.Column('overall_risk_level', sa.String(length=20), nullable=True, comment='整体风险等级'),
    sa.Column('overall_risk_score', sa.Float(), nullable=True, comment='整体风险评分'),
    sa.Column('recommendation', sa.Text(), nullable=True, comment='审查建议'),
    sa.Column('clause_reviews', sa.Text(), nullable=True, comment='条款审查结果 (JSON)'),
    sa.Column('rule_violations', sa.Text(), nullable=True, comment='规则违规项 (JSON)'),
    sa.Column('summary', sa.Text(), nullable=True, comment='审查摘要 (JSON)'),
    sa.Column('model_version', sa.String(length=50), nullable=True, comment='模型版本'),
    sa.Column('review_duration_seconds', sa.Integer(), nullable=True, comment='审查耗时（秒）'),
    sa.Column('reviewer_id', sa.Integer(), nullable=True, comment='人工复核人 ID'),
    sa.Column('review_status', sa.String(length=20), nullable=True, comment='ai_done | reviewed | confirmed'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id')
    )
    op.create_table('approval_flows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('flow_template_id', sa.Integer(), nullable=True, comment='流程模板 ID'),
    sa.Column('flow_type', sa.String(length=50), nullable=True, comment='流程类型'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='流程状态'),
    sa.Column('current_node_id', sa.String(length=50), nullable=True, comment='当前节点 ID'),
    sa.Column('current_step', sa.Integer(), nullable=True, comment='当前步骤'),
    sa.Column('total_steps', sa.Integer(), nullable=True, comment='总步骤数'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('duration_hours', sa.Float(), nullable=True, comment='耗时（小时）'),
    sa.Column('comment', sa.Text(), nullable=True, comment='流程备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_flow_contract', 'approval_flows', ['contract_id'], unique=False)
    op.create_index('idx_flow_status', 'approval_flows', ['status'], unique=False)
    op.create_table('contract_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True, comment='合同内容'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='文件路径'),
    sa.Column('file_type', sa.String(length=10), nullable=True, comment='文件类型'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小'),
    sa.Column('file_hash', sa.String(length=64), nullable=True, comment='文件哈希'),
    sa.Column('change_description', sa.Text(), nullable=True, comment='变更说明'),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False, comment='预警类型'),
    sa.Column('alert_level', sa.String(length=20), nullable=False, comment='预警等级'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='预警标题'),
    sa.Column('message', sa.Text(), nullable=True, comment='预警内容'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='来源：ai | rule | manual'),
    sa.Column('source_detail', sa.Text(), nullable=True, comment='来源详情 (JSON)'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='pending | processing | resolved | ignored'),
    sa.Column('handler_id', sa.Integer(), nullable=True, comment='处理人 ID'),
    sa.Column('handle_comment', sa.Text(), nullable=True, comment='处理意见'),
    sa.Column('handle_time', sa.DateTime(), nullable=True, comment='处理时间'),
    sa.Column('related_clause', sa.String(length=100), nullable=True, comment='相关条款'),
    sa.Column('legal_basis', sa.Text(), nullable=True, comment='法律依据'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seal_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False, comment='合同 ID'),
    sa.Column('contract_no', sa.String(length=50), nullable=False, comment='合同编号'),
    sa.Column('seal_type', sa.String(length=50), nullable=False, comment='用印类型：公章 | 合同章 | 财务章'),
    sa.Column('seal_method', sa.String(length=50), nullable=True, comment='用印方式：电子 | 物理'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='pending | approved | completed | rejected'),
    sa.Column('approver_id', sa.Integer(), nullable=True, comment='审批人 ID'),
    sa.Column('approver_name', sa.String(length=50), nullable=True, comment='审批人姓名'),
    sa.Column('approval_time', sa.DateTime(), nullable=True, comment='审批时间'),
    sa.Column('approval_comment', sa.Text(), nullable=True, comment='审批意见'),
    sa.Column('seal_time', sa.DateTime(), nullable=True, comment='用印时间'),
    sa.Column('seal_operator', sa.String(length=50), nullable=True, comment='用印操作人'),
    sa.Column('seal_image_path', sa.String(length=500), nullable=True, comment='用印照片路径'),
    sa.Column('comment', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_seal_contract', 'seal_records', ['contract_id'], unique=False)
    op.create_index('idx_seal_status', 'seal_records', ['status'], unique=False)
    op.create_index('idx_seal_type', 'seal_records', ['seal_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('real_name', sa.String(length=50), nullable=False, comment='真实姓名'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='部门 ID'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='角色 ID'),
    sa.Column('status', sa.Integer(), nullable=True, comment='1:启用 0:禁用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_user_department', 'users', ['department_id'], unique=False)
    op.create_index('idx_user_role', 'users', ['role_id'], unique=False)
    op.create_index('idx_user_username', 'users', ['username'], unique=False)
    op.create_table('approval_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False, comment='步骤序号'),
    sa.Column('node_id', sa.String(length=50), nullable=False, comment='节点 ID'),
    sa.Column('node_name', sa.String(length=100), nullable=True, comment='节点名称'),
    sa.Column('approver_id', sa.Integer(), nullable=False, comment='审批人 ID'),
    sa.Column('approver_name', sa.String(length=50), nullable=True, comment='审批人姓名'),
    sa.Column('action', sa.String(length=20), nullable=True, comment='审批动作'),
    sa.Column('comment', sa.Text(), nullable=True, comment='审批意见'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='节点状态'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('complete_time', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('duration_hours', sa.Float(), nullable=True, comment='处理耗时'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['approval_flows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_step_approver', 'approval_steps', ['approver_id'], unique=False)
    op.create_index('idx_step_flow', 'approval_steps', ['flow_id'], unique=False)
    op.create_index('idx_step_status', 'approval_steps', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_step_status', table_name='approval_steps')
    op.drop_index('idx_step_flow', table_name='approval_steps')
    op.drop_index('idx_step_approver', table_name='approval_steps')
    op.drop_table('approval_steps')
    op.drop_index('idx_user_username', table_name='users')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_index('idx_user_department', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_seal_type', table_name='seal_records')
    op.drop_index('idx_seal_status', table_name='seal_records')
    op.drop_index('idx_seal_contract', table_name='seal_records')
    op.drop_table('seal_records')
    op.drop_table('risk_alerts')
    op.drop_table('contract_versions')
    op.drop_index('idx_flow_status', table_name='approval_flows')
    op.drop_index('idx_flow_contract', table_name='approval_flows')
    op.drop_table('approval_flows')
    op.drop_table('ai_reviews')
    op.drop_index('idx_role_code', table_name='roles')
    op.drop_table('roles')
    op.drop_index('idx_department_path', table_name='departments')
    op.drop_index('idx_department_parent', table_name='departments')
    op.drop_table('departments')
    op.drop_index('idx_type', table_name='contracts')
    op.drop_index('idx_status', table_name='contracts')
    op.drop_index('idx_risk_level', table_name='contracts')
    op.drop_index('idx_department', table_name='contracts')
    op.drop_index('idx_creator', table_name='contracts')
    op.drop_index('idx_counterparty', table_name='contracts')
    op.drop_index('idx_contract_no', table_name='contracts')
    op.drop_table('contracts')
    op.drop_index('idx_ledger_type', table_name='contract_ledger')
    op.drop_index('idx_ledger_time', table_name='contract_ledger')
    op.drop_index('idx_ledger_status', table_name='contract_ledger')
    op.drop_index('idx_ledger_no', table_name='contract_ledger')
    op.drop_index('idx_ledger_counterparty', table_name='contract_ledger')
    op.drop_index('idx_ledger_contract', table_name='contract_ledger')
    op.drop_table('contract_ledger')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
